version: '2'

services:
    web:
        image: nginx:1.13-alpine
        ports:
            - "80:80"
        volumes:
            - ./lumen:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network

    php:
        image: php:7.1-fpm-jessie
        volumes:
            - ./lumen:/code
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
